### ISSUE TITLE
How to change diff data or cancel audit entry insertion

### ISSUE THREAD

**Issue by gam6itko** [DamienHarper/auditor-bundle#147]
Hello. Often when i save my entity which has decimal type property I got audit `diffs` like this:

```json
{"freePayments": {"new": "0", "old": "0.00"}, "closingPercent": {"new": "0", "old": "0.00"}, "foo": {"new": "1", "old": "2"}}
```
```json
{"freePayments": {"new": "20", "old": "20.00"}, "closingPercent": {"new": "7", "old": "7.00"}, "individualTransfer": {"new": null, "old": "[]"}, "bar": {"new": "1", "old": "2"}}
```

As you see this information not about real value changes, it's about format changes. I want to filter meaningless `diffs`. It must be like this

```json
{"foo": {"new": "1", "old": "2"}}
```
```json
{"bar": {"new": "1", "old": "2"}}
```

**How can I modify diffs data before it stores in database?**
**Can I cancel insertion of audit entry at all?**

**Comment by DamienHarper** [comment]
@gam6itko to better understand the problem, can you tell me:
- what is the type (Doctrine type) of `freePayments` and `closingPercent` fields? (integer, decimal, ...)
- what is the PHP type defined in your entity (if any) regarding these two fields? (float, double, string, ...)
- how do you you populate/set/update these values: are they coming from a form? if yes, which type of field is used in the form? (MoneyType, ...)

**Comment by gam6itko** [comment]
Doctrine type: decimal
```xml
<field name="freePayments" type="decimal" precision="6" scale="2" nullable="true"/>
<field name="closingPercent" type="decimal" precision="5" scale="2" nullable="true"/>
```

Php type: float
```php
    /**
     * @var float|null
     */
    protected $freePayments;

    /**
     * @var float|null 
     */
    protected $closingPercent;
```

For update values I use SonataAdmin FormMapper
```php
$formMapper
  ->add('freePayments', IntegerType::class, [
                'required' => false,
                'attr' => ['min' => 0],
            ])
  ->add('closingPercent', PercentType::class, [
                'type' => 'integer',
                'required' => false,
                'scale' => 2,
            ])
```

**Comment by DamienHarper** [comment]
From your config/mapping, at Doctrine level, `freePayments` and `closingPercent` are declared `decimal` so Doctrine will [convert them to strings](https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/types.html#decimal-types) when loading the values from the database to be able to maintain the number of digits before and after the decimal marks (so a value of 0 in the database will be converted to "0.00" by Doctrine).

So, I'm afraid I won't be able to help much here because it is more an issue with Doctrine itself than an issue with the bundle: the bundle compares the values that Doctrine exposes which means the values after they've eventually been converted to another type.

For example:
1. you load your entity from the database => a value of 0 in the db is loaded and converted to "0.00" in the `freePayments` property
2. you set 0 to `freePayments` and persist it to db
3. the audit is triggered and compares what doctrine exposes => old value: "0.00", new value: 0
4. old and new values are different so they're saved in an audit record

**Comment by gam6itko** [comment]
I guessed about it. But this problem needs to be solved. What you think about allow user to modify `[payload][diff]` data of `LifecycleEvent` by EventListener before it will be stored in DB? The approach is like jms-serializer events. If you do not mind I can make PullRequest

**Comment by DamienHarper** [comment]
@gam6itko This is now possible in `master` branch. You can now alter the payload borrowed by an audit event from an even subscriber.
