### ISSUE TITLE
Broken link to documentation in README file

### ISSUE THREAD

**Issue by maxkain** [DamienHarper/auditor-bundle#219]
https://github.com/DamienHarper/auditor-bundle/blob/master/doc/00-index.md
Not found 404

**Comment by DamienHarper** [comment]
Hi @maxkain ,

The problem you face (missing documentation) is due to the fact that you’re browsing the master branch (instable) whereas the latest stable branch is the 3.x one (latest stable release is 3.4.1)

Here is the documentation for 3.4.1: https://github.com/DamienHarper/auditor-bundle/blob/3.x/doc/00-index.md

Let me know if you need some more help/info.
